languageCode = "en"
title = "Hori"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = false
enableGitInfo = false

[pagination]
pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'