[[navbar]]
  identifier = "en-control-plane"
  name = "Control Plane"
  url = "/control-plane/"
  weight = 1
  [[navbar]]
    identifier = "en-destination"
    name = "Destination Controller"
    url = "/control-plane/destination"
    parent = "en-control-plane"
    weight = 1
  [[navbar]]
    identifier = "en-proxy-injector"
    name = "Proxy-Injector Controller"
    url = "/control-plane/proxy-injector"
    parent = "en-proxy-injector"
    weight = 2

[[navbar]]
  identifier = "en-data-plane"
  name = "Data Plane"
  url = "/data-plane/"
  weight = 2
  [[navbar]]
    identifier = "en-proxy-init"
    name = "Proxy-Init"
    url = "/data-plane/proxy-init"
    parent = "en-data-plane"
    weight = 1

[[navbar]]
  identifier = "en-modules"
  name = "Modules"
  url = "/modules/"
  weight = 3
  [[navbar]]
    identifier = "en-certificates"
    name = "Certificates"
    url = "/modules/certificates"
    parent = "en-modules"
    weight = 1
  [[navbar]]
    identifier = "en-timeouts"
    name = "Timeouts"
    url = "/modules/timeouts"
    parent = "en-modules"
    weight = 2
  [[navbar]]
    identifier = "en-linkerd-cli"
    name = "Linkerd CLI"
    url = "/modules/cli"
    parent = "en-modules"
    weight = 3

[[navbar]]
  identifier = "en-changelog"
  name = "Changelog"
  url = "/changelog/"
  weight = 4