[[navbar]]
  identifier = "modules"
  name = "Modules"
  url = "/modules/"
  weight = 1
  [[navbar]]
    identifier = "certificates"
    name = "Certificates"
    url = "/modules/certificates"
    parent = "modules"
    weight = 1
  [[navbar]]
    identifier = "proxy-init"
    name = "Proxy-Init"
    url = "/modules/proxy-init"
    parent = "modules"
    weight = 2
  [[navbar]]
    identifier = "destination"
    name = "Destination Controller"
    url = "/modules/destination"
    parent = "modules"
    weight = 3
  [[navbar]]
    identifier = "en-timeouts"
    name = "Timeouts"
    url = "/modules/timeouts"
    parent = "modules"
    weight = 4
  [[navbar]]
    identifier = "en-linkerd-cli"
    name = "Linkerd CLI"
    url = "/modules/cli"
    parent = "modules"
    weight = 4

[[navbar]]
  identifier = "changelog"
  name = "Changelog"
  url = "/changelog/"
  weight = 2