[[navbar]]
  identifier = "control-plane"
  name = "Control Plane"
  url = "/control-plane/"
  weight = 1
  [[navbar]]
    identifier = "en-destination"
    name = "Destination Controller"
    url = "/control-plane/destination"
    parent = "control-plane"
    weight = 1

[[navbar]]
  identifier = "data-plane"
  name = "Data Plane"
  url = "/data-plane/"
  weight = 2
  [[navbar]]
    identifier = "proxy-init"
    name = "Proxy-Init"
    url = "/data-plane/proxy-init"
    parent = "data-plane"
    weight = 1

[[navbar]]
  identifier = "modules"
  name = "Modules"
  url = "/modules/"
  weight = 3
  [[navbar]]
    identifier = "certificates"
    name = "Certificates"
    url = "/modules/certificates"
    parent = "modules"
    weight = 1
  [[navbar]]
    identifier = "en-timeouts"
    name = "Timeouts"
    url = "/modules/timeouts"
    parent = "modules"
    weight = 2
  [[navbar]]
    identifier = "en-linkerd-cli"
    name = "Linkerd CLI"
    url = "/modules/cli"
    parent = "modules"
    weight = 3

[[navbar]]
  identifier = "changelog"
  name = "Changelog"
  url = "/changelog/"
  weight = 4