[[navbar]]
  identifier = "modules"
  name = "모듈"
  url = "/ko/modules/"
  weight = 1
  [[navbar]]
    identifier = "certificates"
    name = "인증서"
    url = "/ko/modules/certificates"
    parent = "modules"
    weight = 1
  [[navbar]]
    identifier = "proxy-init"
    name = "프록시 초기화"
    url = "/ko/modules/proxy-init"
    parent = "modules"
    weight = 2
  [[navbar]]
    identifier = "destination"
    name = "Destination 컨트롤러"
    url = "/modules/destination"
    parent = "모듈"
    weight = 3
  [[navbar]]
    identifier = "timeouts"
    name = "타임아웃"
    url = "/ko/modules/timeouts"
    parent = "modules"
    weight = 4
  [[navbar]]
    identifier = "linkerd-cli"
    name = "Linkerd CLI"
    url = "/ko/modules/cli"
    parent = "modules"
    weight = 4

[[navbar]]
  identifier = "changelog"
  name = "변경 로그"
  url = "/ko/changelog/"
  weight = 2