[[navbar]]
  identifier = "kr-control-plane"
  name = "제어 플레인"
  url = "/ko/control-plane/"
  weight = 1
  [[navbar]]
    identifier = "kr-destination"
    name = "목적지 컨트롤러"
    url = "/ko/control-plane/destination"
    parent = "kr-control-plane"
    weight = 1
  [[navbar]]
    identifier = "kr-proxy-injector"
    name = "컨트롤 플레인'"
    url = "/ko/control-plane/proxy-injector"
    parent = "kr-control-plane"
    weight = 2

[[navbar]]
  identifier = "kr-data-plane"
  name = "데이터 플레인"
  url = "/ko/data-plane/"
  weight = 2
  [[navbar]]
    identifier = "kr-proxy-init"
    name = "프록시 초기화"
    url = "/ko/data-plane/proxy-init"
    parent = "kr-data-plane"
    weight = 1

[[navbar]]
  identifier = "kr-modules"
  name = "모듈"
  url = "/ko/modules/"
  weight = 3
  [[navbar]]
    identifier = "kr-certificates"
    name = "인증서"
    url = "/ko/modules/certificates"
    parent = "kr-modules"
    weight = 1
  [[navbar]]
    identifier = "kr-timeouts"
    name = "타임아웃"
    url = "/ko/modules/timeouts"
    parent = "kr-modules"
    weight = 2
  [[navbar]]
    identifier = "kr-linkerd-cli"
    name = "Linkerd 커맨드라인 인터페이스"
    url = "/ko/modules/cli"
    parent = "kr-modules"
    weight = 3

[[navbar]]
  identifier = "kr-changelog"
  name = "변경 로그"
  url = "/ko/changelog/"
  weight = 4
